### ISSUE TITLE
Propose URL fetch check for the EFF Secure Messaging Scorecard

### ISSUE THREAD

**Issue by ikisusi** [HowNetWorks/uriteller#13]
Scorecard update is coming up at https://www.eff.org/secure-messaging-scorecard. Adding a check if service providers and application break the crypto protection envelope with URLs would make sense. Ie. with each messaging application include trap URLs in the secure communications and see if the URLs are automagically fetched and by which party to figure out if URLs in the messages leak automatically or not.

**Comment by ikisusi** [comment]
Having problems finding a contact responsible for the EFF scorecard. Tried asking an EFF affiliated friend but he got not that far either. Have to try some generic EFF contacts next unless someone who reads this knows a better route. :)

**Comment by jviide** [comment]
@ikisusi Any news on this front?

**Comment by ikisusi** [comment]
Gave up on this.
