### ISSUE TITLE
Monitor view: Live updating doesn't work on iPad

### ISSUE THREAD

**Issue by jviide** [HowNetWorks/uriteller#2]

**Comment by jviide** [comment]
In further testing this appears to be a false alarm from my part. Live updates on iPad work ok. Can e.g. @evilon double-check and confirm?

**Comment by evilon** [comment]
@jviide Live update on iPad seemed to work. I had to wait a bit, ~30 seconds and new item appeared on the list without user action.

**Comment by jviide** [comment]
Thank you. Closing this.
